import { StyleSheet, Platform } from 'react-native';
import { theme } from '../../theme/theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.white,
  },
  safeArea: {
    backgroundColor: theme.colors.white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 56,
    backgroundColor: theme.colors.white,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '400',
    color: '#333333',
    flex: 1,
    marginLeft: 8,
    textAlign: 'center',
  },
  headerPlaceholder: {
    width: 40,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  envelopeContainer: {
    marginTop: 64,
  },
  envelopeCircle: {
    backgroundColor: '#E9E1F9',
    borderRadius: 999,
    width: 96,
    height: 96,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  envelope: {
    borderWidth: 3,
    borderColor: '#6C2BD9',
    borderRadius: 8,
    width: 60,
    height: 48,
    backgroundColor: theme.colors.white,
    position: 'relative',
  },
  envelopeFlap: {
    position: 'absolute',
    top: -1,
    left: -1,
    right: -1,
    borderTopWidth: 24,
    borderTopColor: '#6C2BD9',
    borderLeftWidth: 30,
    borderLeftColor: 'transparent',
    borderRightWidth: 30,
    borderRightColor: 'transparent',
  },
  checkCircle: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: '#6C2BD9',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A1A1A',
    textAlign: 'center',
    marginTop: 24,
    lineHeight: 24,
  },
  subtitle: {
    fontSize: 14,
    fontWeight: '400',
    color: '#5F5F5F',
    textAlign: 'center',
    marginTop: 8,
  },
  emailContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    height: 40,
  },
  avatar: {
    backgroundColor: '#C4C4C4',
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emailText: {
    fontSize: 14,
    fontWeight: '400',
    color: '#333333',
    marginLeft: 8,
  },
  infoBox: {
    marginTop: 32,
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    width: 312,
    minHeight: 60,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoText: {
    fontSize: 13,
    fontWeight: '400',
    color: '#4B4B4B',
    flex: 1,
    marginLeft: 8,
    lineHeight: 18,
  },
  spacer: {
    height: 60,
  },
});