import { StyleSheet } from 'react-native';
import { theme } from '@/app/src/theme/theme';

export const TelaVerificacaoEmailStyles = StyleSheet.create({
  scrollView: {
    flex: 1,
    backgroundColor: theme.colors.white,
  },
  content: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: theme.spacing.md,
    paddingHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.lg,
  },
  backButton: {
    padding: theme.spacing.xs,
  },
  headerTitle: {
    fontSize: theme.typography.sizes.lg,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.gray700,
    fontFamily: theme.fonts.body,
    marginLeft: theme.spacing.md,
  },
  centeredContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.lg,
  },
  innerContent: {
    width: '100%',
    maxWidth: 400,
  },
  titleSection: {
    alignItems: 'center',
    marginBottom: theme.spacing.xl,
  },
  iconContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: theme.colors.primary[50],
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: theme.spacing.lg,
  },
  title: {
    fontSize: theme.typography.sizes.xl,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.gray800,
    fontFamily: theme.fonts.heading,
    textAlign: 'center',
    marginBottom: theme.spacing.sm,
  },
  subtitle: {
    fontSize: theme.typography.sizes.md,
    color: theme.colors.gray600,
    fontFamily: theme.fonts.body,
    textAlign: 'center',
    marginBottom: theme.spacing.xs,
    lineHeight: 22,
  },
  emailText: {
    fontSize: theme.typography.sizes.md,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.primary[500],
    fontFamily: theme.fonts.body,
    textAlign: 'center',
    marginTop: theme.spacing.xs,
  },
  codigoSection: {
    marginBottom: theme.spacing.xl,
  },
  instructionText: {
    fontSize: theme.typography.sizes.md,
    color: theme.colors.gray700,
    fontFamily: theme.fonts.body,
    marginBottom: theme.spacing.md,
    textAlign: 'center',
  },
  codigoContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.md,
  },
  codigoInput: {
    width: 48,
    height: 56,
    borderWidth: 2,
    borderColor: theme.colors.gray300,
    borderRadius: theme.borderRadius.md,
    fontSize: theme.typography.sizes.xl,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.gray800,
    fontFamily: theme.fonts.heading,
    backgroundColor: theme.colors.white,
  },
  codigoInputFilled: {
    borderColor: theme.colors.primary[500],
    backgroundColor: theme.colors.primary[50],
  },
  helperText: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.gray500,
    fontFamily: theme.fonts.body,
    textAlign: 'center',
    marginTop: theme.spacing.xs,
  },
  infoSection: {
    marginBottom: theme.spacing.xl,
  },
  resendSection: {
    alignItems: 'center',
  },
  successMessage: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.success + '10',
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.borderRadius.md,
    marginBottom: theme.spacing.md,
  },
  successText: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.success,
    fontFamily: theme.fonts.body,
    marginLeft: theme.spacing.xs,
  },
  resendText: {
    fontSize: theme.typography.sizes.md,
    color: theme.colors.gray600,
    fontFamily: theme.fonts.body,
    marginBottom: theme.spacing.xs,
  },
  resendLink: {
    fontSize: theme.typography.sizes.md,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.primary[500],
    fontFamily: theme.fonts.body,
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timerText: {
    fontSize: theme.typography.sizes.md,
    color: theme.colors.gray600,
    fontFamily: theme.fonts.body,
  },
  verifyButton: {
    backgroundColor: theme.colors.primary[500],
    borderRadius: theme.borderRadius.md,
    paddingVertical: theme.spacing.md,
    alignItems: 'center',
    marginBottom: theme.spacing.lg,
  },
  disabledButton: {
    backgroundColor: theme.colors.gray300,
  },
  verifyButtonText: {
    color: theme.colors.white,
    fontWeight: theme.typography.weights.bold,
    fontSize: theme.typography.sizes.md,
    fontFamily: theme.fonts.body,
  },
  termsText: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.gray500,
    fontFamily: theme.fonts.body,
    textAlign: 'center',
    lineHeight: 20,
  },
  termsLink: {
    color: theme.colors.primary[500],
    fontWeight: theme.typography.weights.bold,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: theme.spacing.lg,
  },
  modalContent: {
    backgroundColor: theme.colors.white,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.xl,
    alignItems: 'center',
    maxWidth: 400,
    width: '100%',
  },
  modalIconContainer: {
    marginBottom: theme.spacing.lg,
  },
  modalTitle: {
    fontSize: theme.typography.sizes.xl,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.gray800,
    fontFamily: theme.fonts.heading,
    textAlign: 'center',
    marginBottom: theme.spacing.md,
  },
  modalText: {
    fontSize: theme.typography.sizes.md,
    color: theme.colors.gray600,
    fontFamily: theme.fonts.body,
    textAlign: 'center',
    lineHeight: 22,
  },
});