import { StyleSheet, Platform } from 'react-native';
import { theme } from '@/app/src/theme/theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.gray50,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
    backgroundColor: theme.colors.white,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.gray200,
    ...Platform.select({
      ios: theme.shadows.sm,
      android: theme.shadows.sm,
    }),
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: theme.typography.sizes.lg,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.gray800,
  },
  headerCount: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.gray600,
    marginRight: theme.spacing.md,
  },
  listContainer: {
    padding: theme.spacing.md,
    paddingBottom: theme.spacing.xl,
  },
  listContainerEmpty: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  card: {
    margin: 0,
    marginBottom: theme.spacing.md,
    padding: 0,
    borderRadius: theme.borderRadius.lg,
    borderWidth: 0,
    backgroundColor: theme.colors.white,
    ...theme.shadows.md,
  },
  vendidoCard: {
    opacity: 0.7,
    backgroundColor: theme.colors.gray100,
  },
  cardContent: {
    flexDirection: 'row',
    padding: theme.spacing.md,
  },
  imageContainer: {
    position: 'relative',
    width: 100,
    height: 100,
    marginRight: theme.spacing.md,
  },
  productImage: {
    width: '100%',
    height: '100%',
    borderRadius: theme.borderRadius.md,
  },
  productImageVendido: {
    opacity: 0.5,
  },
  destaqueTag: {
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: theme.colors.primary[500],
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
    borderTopLeftRadius: theme.borderRadius.md,
    borderBottomRightRadius: theme.borderRadius.md,
  },
  destaqueText: {
    color: theme.colors.white,
    fontSize: theme.typography.sizes.xs,
    fontWeight: theme.typography.weights.bold,
  },
  vendidoOverlay: {
    position: 'absolute',
    top: theme.spacing.sm,
    right: theme.spacing.sm,
    backgroundColor: theme.colors.gray600,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
    borderRadius: theme.borderRadius.sm,
    zIndex: 10,
  },
  vendidoText: {
    color: theme.colors.white,
    fontSize: theme.typography.sizes.xs,
    fontWeight: theme.typography.weights.bold,
  },
  infoContainer: {
    flex: 1,
    position: 'relative',
  },
  favoriteButton: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: 'transparent',
    zIndex: 10,
    padding: theme.spacing.xs,
  },
  favoriteButtonVendido: {
    opacity: 0.5,
  },
  textContent: {
    flex: 1,
    marginTop: theme.spacing.sm,
  },
  productName: {
    fontSize: theme.typography.sizes.md,
    fontWeight: theme.typography.weights.medium,
    color: theme.colors.gray800,
    marginBottom: theme.spacing.xs,
  },
  productNameVendido: {
    color: theme.colors.gray500,
    textDecorationLine: 'line-through',
  },
  productPrice: {
    fontSize: theme.typography.sizes.lg,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.primary[500],
    marginBottom: theme.spacing.sm,
  },
  productPriceVendido: {
    color: theme.colors.gray500,
    textDecorationLine: 'line-through',
  },
  vendidoMessage: {
    color: theme.colors.gray500,
    fontSize: theme.typography.sizes.sm,
    fontStyle: 'italic',
    marginBottom: theme.spacing.sm,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.spacing.xs,
  },
  productLocation: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.gray600,
    marginLeft: theme.spacing.xs,
    flex: 1,
  },
  productLocationVendido: {
    color: theme.colors.gray500,
  },
  categoriaContainer: {
    alignSelf: 'flex-start',
    backgroundColor: theme.colors.primary[50],
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
    borderRadius: theme.borderRadius.sm,
    marginBottom: theme.spacing.xs,
  },
  categoriaText: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.primary[600],
    fontWeight: theme.typography.weights.medium,
  },
  condicaoContainer: {
    alignSelf: 'flex-start',
    backgroundColor: theme.colors.gray100,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
    borderRadius: theme.borderRadius.sm,
  },
  condicaoText: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.gray700,
    fontWeight: theme.typography.weights.medium,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: theme.spacing.xl,
  },
  emptyIconContainer: {
    marginBottom: theme.spacing.lg,
  },
  emptyTitle: {
    fontSize: theme.typography.sizes.xl,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.gray800,
    marginBottom: theme.spacing.sm,
    textAlign: 'center',
  },
  emptyText: {
    fontSize: theme.typography.sizes.md,
    color: theme.colors.gray600,
    textAlign: 'center',
    marginBottom: theme.spacing.xl,
    lineHeight: 24,
  },
  exploreButton: {
    backgroundColor: theme.colors.secondary[500],
    paddingVertical: theme.spacing.md,
    paddingHorizontal: theme.spacing.xl,
    borderRadius: theme.borderRadius.lg,
  },
  exploreButtonText: {
    fontSize: theme.typography.sizes.md,
    fontWeight: theme.typography.weights.semibold,
    color: theme.colors.white,
    marginLeft: theme.spacing.sm,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: theme.colors.gray500,
    textAlign: 'center',
  },
  errorContainer: {
    backgroundColor: theme.colors.error + '20',
    padding: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  errorText: {
    color: theme.colors.error,
    marginLeft: 8,
    flex: 1,
  },
  dataPublicacao: {
    fontSize: 12,
    color: theme.colors.gray500,
    marginTop: 4,
    fontStyle: 'italic',
  },
});